sudo: required
language: go
os:
    - osx
go:
    - "1.10"

go_import_path: github.com/versent/saml2aws

install:
    - echo noop

env:
    - "PATH=/home/travis/gopath/bin:$PATH"

before_script:
    - "export DISPLAY=:99.0"
    - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then sh ci/before_script_linux.sh; fi
            
script:
    - make ci

addons:
    apt:
        packages:
        - build-essential
        - fakeroot
        - git
        - libsecret-1-dev
