steps:

  - wait

  - name: ":vertical_traffic_light: Tests"
    command: "make test"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: saml2aws

  - wait

  - name: ":hammer: Compile"
    command: "make compile"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: saml2aws

  - wait

  - name: ":package: Package"
    command: "make dist"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: saml2aws

  - block: ':shipit: Release'
    branches: 'master'

  - name: ':github: Release'
    command: 'make release'
    artifact_paths: 'release/**/*'
    branches: 'master'

  - wait